image: "jpetazzo/dind"
script:
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_10.x | bash
  - apt-get install nodejs
  - npm install
  - npm run-script build
  - docker build -t result .
